sudo: false

language: node_js

cache:
  directories:
    - ~/.npm

notifications:
  email: false

node_js:
  - "8"
  - "10"
  - "12"

install: yarn install

script:
  - yarn run lint
  - yarn run test
